# Generated by Django 5.1.7 on 2025-07-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningmaterial',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
