# Generated by Django 5.1.7 on 2025-07-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0002_listeningmaterial_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('format_error', '格式有誤'), ('wrong_part', '不符合相對應 Part'), ('content_error', '內文有誤'), ('question_error', '題目有誤')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='readingpassage',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('format_error', '格式有誤'), ('wrong_part', '不符合相對應 Part'), ('content_error', '內文有誤'), ('question_error', '題目有誤')], max_length=50, null=True),
        ),
    ]
