# Generated by Django 5.1.7 on 2025-07-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0004_alter_listeningmaterial_accent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('reading', 'Reading'), ('listen', 'Listening'), ('mixed', 'Mixed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='time_limit_enabled',
            field=models.BooleanField(default='20'),
        ),
        migrations.AlterField(
            model_name='listeningmaterial',
            name='accent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listeningmaterial',
            name='audio_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listeningmaterial',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
