# Generated by Django 5.1.7 on 2025-07-23 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0005_alter_exam_exam_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_approved',
        ),
    ]
