# Generated by Django 5.1.7 on 2025-07-28 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0007_remove_question_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='vocab_score',
        ),
    ]
