# Generated by Django 5.1.7 on 2025-05-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0003_rename_customuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('vocab', 'Vocabulary'), ('reading', 'Reading'), ('listen', 'Listening')], default='vocab', max_length=20)),
                ('question_text', models.TextField()),
                ('option_a_text', models.TextField()),
                ('option_b_text', models.TextField()),
                ('option_c_text', models.TextField()),
                ('option_d_text', models.TextField()),
                ('is_correct', models.CharField(max_length=1)),
                ('difficulty_level', models.IntegerField(default=1)),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
